# Generated by Django 3.2.6 on 2023-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
