# Generated by Django 3.2.6 on 2023-10-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(blank=True, default=None, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
                ('velocidad', models.FloatField(blank=True, default=None, null=True)),
                ('aceleracion', models.FloatField(blank=True, default=None, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodo.nodo')),
            ],
        ),
    ]
