# Generated by Django 3.2.6 on 2023-11-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_measurements_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='azimuth',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='positionDOP',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='latitud',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='longitud',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
